"""Generate guardrails.md-compatible output from NightWatch findings for Ralph."""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger("nightwatch.guardrails")


def _slugify(text: str) -> str:
    """Convert text to a URL-friendly slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return text[:50]


def _extract_module(transaction: str) -> str:
    """Extract a readable module name from a transaction name."""
    if "#" in transaction:
        return transaction.split("#")[0]
    return transaction.split("/")[-1] if "/" in transaction else transaction


def _generate_sign(analysis: dict[str, Any], index: int) -> str:
    """Generate a Ralph-compatible Sign from an analysis."""
    error_class = analysis.get("error_class", "Unknown")
    transaction = analysis.get("transaction", "Unknown")
    root_cause = analysis.get("root_cause", "No root cause identified")
    module = _extract_module(transaction)

    return (
        f"### Sign {index}: {error_class} in {module}\n\n"
        f"- **Trigger**: When modifying code in `{module}` or related modules\n"
        f"- **Instruction**: Watch for {error_class} — {root_cause[:200]}\n"
        f"- **Added after**: NightWatch analysis on "
        f"{analysis.get('date', 'unknown date')}\n"
        f"- **Example**: `{transaction}` experienced this error in production\n"
    )


def generate_guardrails(
    report_data: dict[str, Any], output_path: str | None = None
) -> str:
    """Generate guardrails.md content from a NightWatch run report.

    Only includes high-confidence analyses (confidence >= 0.7).
    """
    lines = [
        "# NightWatch Guardrails\n",
        (
            "> Auto-generated by NightWatch. These signs help prevent "
            "recurring production errors.\n"
        ),
        "## Production Error Signs\n",
    ]

    sign_index = 1
    for analysis in report_data.get("errors_analyzed", []):
        confidence = analysis.get("confidence", 0.0)
        if confidence >= 0.7:
            lines.append(_generate_sign(analysis, sign_index))
            sign_index += 1

    for pattern in report_data.get("patterns_detected", []):
        if pattern.get("confidence", 0.0) >= 0.7:
            lines.append(
                f"### Sign {sign_index}: "
                f"Recurring {pattern.get('error_class', 'Unknown')}\n\n"
                f"- **Trigger**: When working on affected transactions\n"
                f"- **Instruction**: This error has occurred "
                f"{pattern.get('count', 'multiple')} times. "
                f"{pattern.get('suggested_action', 'Investigate root cause.')}\n"
                f"- **Added after**: Pattern detected by NightWatch\n"
            )
            sign_index += 1

    if sign_index == 1:
        lines.append("_No high-confidence signs generated from this run._\n")

    content = "\n".join(lines)

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        logger.info(f"Guardrails written to {output_path}")

    return content
